services:
  ccm_frontend:
    build: ./ccm_frontend
    container_name: ccm_frontend
    expose:
      - "80"
    networks:
      - network_services

  ccm_backend:
    build: ./ccm_backend
    container_name: ccm_backend
    expose:
      - "5000"
    networks:
      - network_services

  nginx:
    image: nginx:latest
    container_name: ccm_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ccm_frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - ccm_frontend
      - ccm_backend
    networks:
      - network_services

networks:
  network_services:
    driver: bridge
