services:
  ccm_frontend:
    container_name: ccm_frontend
    image: ccm_frontend
    build:
      context: ccm_frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    networks:
      - network_services
    restart: always

  ccm_backend:
    container_name: ccm_backend
    image: ccm_backend
    build:
      context: ccm_backend
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    networks:
      - network_services
    restart: always

  nginx:
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    container_name: ccm_nginx
    ports:
      - "80:80"
    depends_on:
      - ccm_frontend
      - ccm_backend
    networks:
      - network_services
    restart: always
    environment:
      TZ: "Asia/Bangkok"

networks:
  network_services:
    driver: bridge
