services:
  ccm_frontend:
    container_name: ccm_frontend
    image: ccm_frontend
    build:
      context: ccm_frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:30517300
    networks:
      - network_services
    restart: always

  ccm_backend:
    container_name: ccm_backend
    image: ccm_backend
    build:
      context: ccm_backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    networks:
      - network_services
    restart: always

  nginx:
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - network_services
    restart: always
    environment:
      TZ: "Asia/Bangkok"

networks:
  network_services:
    driver: bridge
